// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItW_fQ8riUVgiPAUP4uOtkgWDzyKAUoo',
    appId: '1:879311207334:web:955d33945069361d12ed67',
    messagingSenderId: '879311207334',
    projectId: 'currensee-636ed',
    authDomain: 'currensee-636ed.firebaseapp.com',
    storageBucket: 'currensee-636ed.firebasestorage.app',
    measurementId: 'G-77XL514Z8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_YDivmQ7p4A6PqC2_xL6VIgOtl0Hv-Y',
    appId: '1:879311207334:android:905775b5ade8ef2f12ed67',
    messagingSenderId: '879311207334',
    projectId: 'currensee-636ed',
    storageBucket: 'currensee-636ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_x-EubF-RdoaiXYOtT07A_Oj_5oU2ISM',
    appId: '1:879311207334:ios:671943dbb132dd0012ed67',
    messagingSenderId: '879311207334',
    projectId: 'currensee-636ed',
    storageBucket: 'currensee-636ed.firebasestorage.app',
    androidClientId: '879311207334-dk5k798ekbbjju0rtjmg12vih1kb6a90.apps.googleusercontent.com',
    iosClientId: '879311207334-3df3hoi0mnq1h4ll6m394rlb2g5se2ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.currenSee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItW_fQ8riUVgiPAUP4uOtkgWDzyKAUoo',
    appId: '1:879311207334:web:f945da99686d0e1012ed67',
    messagingSenderId: '879311207334',
    projectId: 'currensee-636ed',
    authDomain: 'currensee-636ed.firebaseapp.com',
    storageBucket: 'currensee-636ed.firebasestorage.app',
    measurementId: 'G-5HG9H21VDC',
  );

}